let g1 = new Graph()
g1.insertVertex('a')
g1.insertVertex('b')
g1.insertVertex('c')
g1.insertVertex('d')
g1.insertVertex('e')
g1.insertVertex('f')
g1.insertVertex('g')
g1.insertVertex('h')
g1.insertEdge('a', 'b', 3)
g1.insertEdge('a', 'f', 16)
g1.insertEdge('a', 'd', 2)
g1.insertEdge('b', 'd', 5)
g1.insertEdge('b', 'c', 15)
g1.insertEdge('c', 'd', 16)
g1.insertEdge('c', 'e', 10)
g1.insertEdge('c', 'h', 11)
g1.insertEdge('c', 'f', 12)
g1.insertEdge('d', 'f', 17)
g1.insertEdge('d', 'e', 13)
g1.insertEdge('e', 'f', 12)
g1.insertEdge('e', 'g', 8)
g1.insertEdge('e', 'h', 2)
g1.insertEdge('f', 'g', 4)
g1.insertEdge('g', 'h', 9)

let g2 = new Graph()
g2.insertVertex('a')
g2.insertVertex('b')
g2.insertVertex('c')
g2.insertVertex('d')
g2.insertVertex('e')
g2.insertVertex('f')
g2.insertVertex('g')
g2.insertVertex('h')
g2.insertEdge('a', 'b', 1)
g2.insertEdge('a', 'c', 1)
g2.insertEdge('a', 'd', 1)
g2.insertEdge('b', 'e', 1)
g2.insertEdge('b', 'c', 1)
g2.insertEdge('c', 'f', 1)
g2.insertEdge('c', 'e', 1)
g2.insertEdge('d', 'f', 1)
g2.insertEdge('d', 'h', 1)
g2.insertEdge('e', 'g', 1)
g2.insertEdge('f', 'g', 1)
g2.insertEdge('g', 'h', 1)

let g3 = new Graph()
g3.insertVertex('a')
let start = g3.vertices['a']
g3.insertVertex('b')
g3.insertVertex('c')
g3.insertVertex('d')
g3.insertVertex('e')
g3.insertVertex('f')
g3.insertEdge('a', 'b', 2)
g3.insertEdge('a', 'f', 16)
g3.insertEdge('a', 'd', 17)
g3.insertEdge('b', 'd', 5)
g3.insertEdge('b', 'c', 15)
g3.insertEdge('c', 'd', 163)
g3.insertEdge('c', 'e', 11)
g3.insertEdge('d', 'f', 9)
g3.insertEdge('d', 'e', 8)
g3.insertEdge('e', 'f', 12)

console.log(Prim(g3, start));
console.log(Kruskal(g1));
console.log(DFS(g2))
